services:
  - type: web
    name: feedback-api
    runtime: python
    buildCommand: |
      pip install -r requirements.txt
      echo "=== Estrutura de diretórios após build ==="
      ls -l
      echo "=== Conteúdo do diretório atual ==="
      pwd
      ls -la
      echo "=== Verificando arquivo Python ==="
      ls -l *.py
    startCommand: |
      echo "Verificando arquivo feedback_server.py..."
      ls -l feedback_server.py
      echo "Iniciando aplicação..."
      gunicorn --pythonpath /opt/render/project/src feedback_server:app
    envVars:
      - key: CSV_PATH
        value: /data/feedbacks.csv
      - key: PORT
        value: 8000
