services:
  - type: web
    name: feedback-api
    runtime: python
    buildCommand: |
      echo "=== Usando Procfile ==="
      cat Procfile
      pip install -r requirements.txt
      echo "=== Arquivos no diretório ==="
      ls -la
    startCommand: |
      echo "=== Verificando configuração ==="
      echo "Arquivo feedback_server.py existe? $(ls feedback_server.py 2>/dev/null && echo Sim || echo Não)"
      echo "Conteúdo do Procfile:"
      cat Procfile
      echo "Executando aplicação conforme Procfile..."
      gunicorn --pythonpath . feedback_server:app
    envVars:
      - key: CSV_PATH
        value: /data/feedbacks.csv
      - key: PORT
        value: 8000
    useProcfile: true  # Força o uso do Procfile
